# Generated by Django 6.0.2 on 2026-03-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_birth_date_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin_color',
            field=models.CharField(default='#2196F3', help_text='Hex color code for the map pin', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pin_emoji',
            field=models.CharField(blank=True, help_text="Emoji to display if icon_type is 'emoji'", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pin_icon_type',
            field=models.CharField(choices=[('none', 'None'), ('emoji', 'Emoji'), ('initials', 'Initials'), ('picture', 'Profile Picture')], default='none', help_text='What to display inside the pin', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pin_style',
            field=models.CharField(choices=[('teardrop', 'Teardrop'), ('circle', 'Circle'), ('square', 'Square'), ('triangle', 'Triangle'), ('diamond', 'Diamond')], default='teardrop', help_text='Shape of the map pin', max_length=20),
        ),
    ]
