# Generated by Django 6.0.2 on 2026-02-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
