# Generated by Django 6.0.2 on 2026-03-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pin_color',
            field=models.CharField(default='#F44336', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='pin_emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='pin_icon_type',
            field=models.CharField(choices=[('none', 'None'), ('emoji', 'Emoji'), ('initials', 'Initials'), ('picture', 'Picture')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='pin_style',
            field=models.CharField(choices=[('teardrop', 'Teardrop'), ('circle', 'Circle'), ('square', 'Square'), ('triangle', 'Triangle'), ('diamond', 'Diamond')], default='teardrop', max_length=20),
        ),
    ]
