# Generated by Django 6.0.2 on 2026-04-26 20:09
# Edited by Task 7 of the Firestore migration: airports/stations are no
# longer Django models (they moved to an in-memory reference index), so
# these fields are plain integer IDs rather than ForeignKeys.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_person_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='preferred_airport',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='preferred_station',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
