# Generated by Django 6.0.2 on 2026-04-26 20:09
# Edited by Task 7 of the Firestore migration: airports/stations are no
# longer Django models (they moved to an in-memory reference index), so
# these fields are plain integer IDs rather than ForeignKeys.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_person_preferred_airport_person_preferred_station'),
        ('trips', '0003_trip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripstop',
            name='person',
        ),
        migrations.AddField(
            model_name='tripstop',
            name='airport',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='people',
            field=models.ManyToManyField(blank=True, to='people.person'),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='station',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
