# Generated by Django 6.0.2 on 2026-03-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_station_station_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.CharField(choices=[('major_station', 'Major Station'), ('commuter_rail_station', 'Commuter Rail Station'), ('subway_station', 'Subway Station'), ('regional_station', 'Regional Station')], default='major_station', max_length=25),
        ),
    ]
